version: '3.7'
services:
  postgres:
    image: "postgres:12-alpine"
    environment:
      - 'POSTGRES_USER=ptklocal'
      - 'POSTGRES_PASSWORD=ptklocal'
      - 'POSTGRES_DB=ptklocal'
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
