[tool.poetry]
name = "reader"
version = "0.1.0"
description = ""
authors = ["nhanb"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0.5"
psycopg2 = "^2.8.5"

[tool.poetry.dev-dependencies]
python-language-server = "^0.31.10"
flake8 = "^3.7.9"
ipdb = "^0.13.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
