[tool.poetry]
name = "pytaku"
version = "0.1.1"
description = ""
authors = ["Bùi Thành Nhân <hi@imnhan.com>"]
license = "AGPL-3.0-only"

[tool.poetry.scripts]
pytaku-migrate = "pytaku:migrate"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
